theme: jekyll-theme-minimal
title: Quinn Thomas, Ph.D.
description: "Professor | Virginia Tech | Co-Director of Virginia Tech Center for Ecosystem Forecasting | Cathie and Tom WotekiÂ Data Science Faculty Fellow"
logo: assets/RQ_Thomas_head_shot_small_circle.png
github:
  is_project_page: false
